name: "git-flow workflow"
description: "This GitHub Action takes care of the release hustle: it auto-assigns versions to commits on your primary branch, creates release tags, and publishes GitHub Releases — all following Git Flow. You write the code, it does the rest"
author: "kvendingoldo"

branding:
  icon: "play-circle"
  color: "green"

inputs:
  init_version:
    description: "The initial project version used for the first Git tag (e.g., 0.0.0)"
    required: false
    default: "0.0.0"
  primary_branch:
    description: "The main development branch (e.g., main or master)"
    required: false
    default: "main"
  tag_prefix_candidate:
    description: "Prefix applied to non-release Git tags"
    required: false
    default: "rc/"
  tag_prefix_release:
    description: "Prefix applied to release Git tags"
    required: false
    default: ""
  github_api_url:
    description: "Base URL for the GitHub API"
    required: false
    default: "https://api.github.com"
  github_token:
    description: "GitHub token used for authentication (the built-in GITHUB_TOKEN secret can be used)"
    required: false
    default: ""
  enable_git_push:
    description: "Whether to push branches/tags to the remote Git repository"
    required: true
    default: "true"
  enable_github_release:
    description: "Whether to create GitHub releases in addition to Git tags (requires github_token)"
    required: false
    default: "true"
  auto_release_branches:
    description: "Whether to automatically create GitHub releases for specific branches"
    required: false
    default: ""
  log_level:
    description: "Verbosity level for logging output (e.g., INFO, DEBUG, ERROR)"
    required: false
    default: "INFO"

outputs:
  version:
    description: "Generated version"
  safe_version:
    description: "Generated version without any specific symbols"

runs:
  using: "docker"
  image: 'Dockerfile'
  #image: "docker://kvendingoldo/git-flow-action:v0.0.1-alpha1"
