codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
        only_pulls: true
    patch:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
        only_pulls: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

ignore:
  - "tests/*"
  - "setup.py"
  - "*.pyc"
  - "*.pyo"
  - "*.pyd"
  - ".git/*"
  - "*.so"
  - "*.egg"
  - "*.egg-info"
  - "dist/*"
  - "build/*"
  - "*.egg-info/*"
